repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '1.8.3'  # Use your Poetry version
    hooks:
      - id: poetry-check
      - id: poetry-export
        args: [
          "-f",
          "requirements.txt",
          "-o",
          "requirements.txt",
          "--extras",
          "dev",
          "--without-hashes",
        ]
        verbose: true
