name: PtyLab
channels:
  - defaults
  - conda-forge 
dependencies:
  - python=3.10
  - numpy
  - cupy
  - h5py
  - matplotlib
  - scipy
  - scikit-image
  - scikit-learn
  - pyqtgraph
  - tqdm
  - tables
  - pip
  - ipython
  - pip:
    - tensorflow-cpu
